version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend_network

  redis:
    image: redis:6
    container_name: redis
    restart: always
    networks:
      - backend_network

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - backend_network
    command: gunicorn --config gunicorn.conf.py config.wsgi:application

  celery_worker:
    build:
      context: ./backend
    container_name: celery_worker
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - backend
      - redis
    command: celery -A config worker --loglevel=info
    networks:
      - backend_network

  celery_beat:
    build:
      context: ./backend
    container_name: celery_beat
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - backend
      - redis
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
