# Generated by Django 5.1.3 on 2024-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='avg_issue_close_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='avg_pr_merge_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='closed_issues_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='merged_pr_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='open_issues_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='top_contributors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='unmerged_pr_count',
            field=models.IntegerField(default=0),
        ),
    ]
