# Generated by Django 5.1.3 on 2024-11-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
