# Generated by Django 5.1.3 on 2024-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_health', '0002_pullrequest_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sentiment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
