# Generated by Django 5.1.3 on 2024-11-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_health', '0004_repository_code_frequency_repository_code_of_conduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='contributions',
            new_name='total_contributions',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='repositories',
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('repository', 'issue_number')},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='contributor_growth_rate',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='fork_growth_rate',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='issue_categories',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='pr_review_count',
        ),
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='median_issue_response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='median_pr_response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'pr_number')},
        ),
        migrations.CreateModel(
            name='RepositoryContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions', models.IntegerField(default=0)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_health.contributor')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_health.repository')),
            ],
            options={
                'unique_together': {('repository', 'contributor')},
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='contributors',
            field=models.ManyToManyField(related_name='repositories', through='github_health.RepositoryContributor', to='github_health.contributor'),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='sentiment',
        ),
    ]
